import type { ReactNode } from 'react';
import { StravaConnectButton } from '@/features/data-import/ui/StravaConnectButton';
import type { StravaAuthStatus } from '@/features/data-import/services/stravaLoader';
import type { StravaAuthIssue } from '@/features/data-import/hooks/useActivityData';
import type { useLongPress } from '@/features/diagnostics/DiagnosticOverlay';
import { getAllThemes } from '@/features/theme/infrastructure/themeRepository';
import { GIFT_TIERS_CLIENT } from '@/features/checkout/ui/tiers';
import { TESTIMONIALS } from './landingData';

interface LandingPageProps {
  stravaAuth: StravaAuthStatus;
  stravaLoading: boolean;
  onConnect: () => void;
  onDisconnect: () => void;
  onRefresh: () => void;
  /** Set when the user connected without activity:read_all, or the session expired. */
  authIssue: StravaAuthIssue | null;
  error: string | null;
  /** Spread onto the logo so a long-press opens the diagnostics overlay. */
  logoLongPress: ReturnType<typeof useLongPress>;
  onGift: () => void;
  onPrivacy: () => void;
}

// Prominent example images, each in a different theme so the page doesn't read as
// black-and-white only (generated by scripts/gen-landing-examples.mjs):
//   hero    — London composite, Coral theme
//   single  — 102 km single run, Japanese Ink theme
//   compose — Budapest composite, Midnight Blue theme
const HERO_IMAGE = '/assets/landing/hero.png';
const SINGLE_EXAMPLE = '/assets/landing/example-single.png';
const COMPOSITE_EXAMPLE = '/assets/landing/example-composite.png';

/**
 * Public landing page (unauthenticated). Mobile-first, scrollable: it answers
 * "what am I buying, how much, and can I trust it?" before asking the visitor to
 * connect Strava. The connect button is repeated at the top, in the hero, and at
 * the foot so the primary action is always one tap away. Auth-recovery alerts
 * (missing scope / expired session) render in the hero, where the CTA lives.
 */
export function LandingPage({
  stravaAuth,
  stravaLoading,
  onConnect,
  onDisconnect,
  onRefresh,
  authIssue,
  error,
  logoLongPress,
  onGift,
  onPrivacy,
}: LandingPageProps) {
  const connectButton = (
    <StravaConnectButton
      auth={stravaAuth}
      loading={stravaLoading}
      onConnect={onConnect}
      onDisconnect={onDisconnect}
      onRefresh={onRefresh}
    />
  );

  return (
    <div className="min-h-dvh bg-[#0a0a0a] text-[#e5e5e5]">
      {/* Sticky top bar — logo + persistent connect CTA */}
      <header className="sticky top-0 z-30 border-b border-white/5 bg-[#0a0a0a]/85 backdrop-blur-sm">
        <div className="mx-auto flex h-14 max-w-5xl items-center justify-between px-5">
          <span
            className="select-none text-xl uppercase tracking-[0.2em]"
            style={{ fontFamily: 'var(--font-display)' }}
            {...logoLongPress}
          >
            RunInk
          </span>
          <div className="hidden sm:block">{connectButton}</div>
        </div>
      </header>

      <main className="mx-auto max-w-5xl px-5">
        {/* ---- Hero ---- */}
        <section className="flex flex-col items-center gap-10 py-12 md:flex-row md:items-center md:gap-12 md:py-20">
          <div className="order-2 w-full text-center md:order-1 md:w-1/2 md:text-left">
            <h1
              className="text-4xl uppercase leading-[0.95] tracking-[0.04em] md:text-6xl"
              style={{ fontFamily: 'var(--font-display)' }}
            >
              Your runs,
              <br />
              as map art.
            </h1>
            <p className="mx-auto mt-5 max-w-md text-sm leading-relaxed text-white/50 md:mx-0 md:text-base">
              RunInk turns your Strava runs into beautiful, printable map posters —
              a single run with its stats, or a whole city of runs layered into one
              heat-map. Design it free, print it if you love it.
            </p>

            {/* Auth-recovery prompts live with the CTA so the user acts, not just reads. */}
            {authIssue?.kind === 'missing_scope' && (
              <div
                role="alert"
                className="mx-auto mt-6 max-w-md rounded-md border border-amber-500/30 bg-amber-900/15 px-4 py-3 text-left text-xs leading-relaxed text-amber-200/90 md:mx-0"
              >
                <div className="mb-1 font-medium text-amber-200">Almost there</div>
                <div className="text-amber-100/80">
                  Strava sent us back without the "View data about your activities"
                  permission. Click Connect again and make sure that checkbox is
                  ticked — it's how we read your runs to make the poster.
                </div>
              </div>
            )}
            {authIssue?.kind === 'session_invalid' && (
              <div
                role="alert"
                className="mx-auto mt-6 max-w-md rounded-md border border-red-500/30 bg-red-900/15 px-4 py-3 text-left text-xs leading-relaxed text-red-200/90 md:mx-0"
              >
                <div className="mb-1 font-medium text-red-200">Your Strava session expired</div>
                <div className="text-red-100/80">Reconnect Strava to pick up where you left off.</div>
              </div>
            )}

            <div className="mt-8 flex flex-col items-center gap-3 md:items-start">
              {connectButton}
              <p className="text-xs text-white/30">
                Free to design &amp; download · prints from{' '}
                {formatPrice(cheapestPriceCents())}
              </p>
            </div>

            {error && <div className="mt-4 text-xs text-red-400/60">{error}</div>}
          </div>

          {/* Hero poster — the asset early users react to most; show it big. */}
          <div className="order-1 w-2/3 max-w-xs md:order-2 md:w-1/2 md:max-w-none">
            <img
              src={HERO_IMAGE}
              alt="Example RunInk poster — every run in London layered into one coral-toned heat-map"
              loading="eager"
              className="mx-auto w-full rounded-lg border border-white/10 shadow-2xl"
            />
          </div>
        </section>

        {/* ---- Two ways to make art ---- */}
        <Section title="Two ways to make a poster">
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
            <ExampleCard
              image={SINGLE_EXAMPLE}
              imageAlt="Single-run poster: one route with distance markers and stats"
              label="Single run"
              description="One run, mapped on its own — with pace, distance markers and a clean route line."
            />
            <ExampleCard
              image={COMPOSITE_EXAMPLE}
              imageAlt="Composite poster: hundreds of Budapest runs layered into one heat-map"
              label="Composite"
              description="Every run in a city, layered into one heat-map-style art piece of your territory."
            />
          </div>
        </Section>

        {/* ---- Themes showcase ---- */}
        <Section
          title="Ten hand-crafted themes"
          subtitle="The same run, ten ways. Pick a look that matches your wall — switch any time while you design."
        >
          <div className="-mx-5 flex snap-x snap-mandatory gap-3 overflow-x-auto px-5 pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
            {getAllThemes().map((theme) => (
              <figure key={theme.id} className="w-32 flex-shrink-0 snap-start sm:w-36">
                <img
                  src={`/assets/landing/themes/${theme.id}.png`}
                  alt={`${theme.name} theme example`}
                  loading="lazy"
                  className="aspect-[4/5] w-full rounded-md border border-white/10 object-cover"
                />
                <figcaption className="mt-2 text-center text-xs text-white/50">{theme.name}</figcaption>
              </figure>
            ))}
          </div>
        </Section>

        {/* ---- Pricing ---- */}
        <Section
          title="Simple, upfront pricing"
          subtitle="Designing and downloading a PNG is always free. Pay only when you want a museum-quality print delivered."
        >
          <div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-5">
            {GIFT_TIERS_CLIENT.map((tier) => (
              <div
                key={tier.id}
                className="flex flex-col rounded-lg border border-white/10 bg-white/[0.02] p-4"
              >
                <div className="text-sm font-medium text-white/90">{tier.name}</div>
                <div className="mt-1 flex-1 text-xs leading-relaxed text-white/40">{tier.description}</div>
                <div
                  className="mt-3 text-2xl"
                  style={{ fontFamily: 'var(--font-display)' }}
                >
                  {formatPrice(tier.priceCents)}
                </div>
              </div>
            ))}
          </div>
          <p className="mt-4 text-center text-xs text-white/30">
            Printed &amp; shipped worldwide by our print partner. Secure checkout via Stripe.
          </p>
        </Section>

        {/* ---- Social proof ---- */}
        <Section title="What runners say">
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            {TESTIMONIALS.map((t) => (
              <figure
                key={t.name}
                className="rounded-lg border border-white/10 bg-white/[0.02] p-6"
              >
                <blockquote
                  className="text-lg leading-snug text-white/80"
                  style={{ fontFamily: 'var(--font-serif)' }}
                >
                  “{t.quote}”
                </blockquote>
                <figcaption className="mt-3 text-xs uppercase tracking-wider text-white/40">
                  — {t.name}
                </figcaption>
              </figure>
            ))}
          </div>
        </Section>

        {/* ---- Final CTA ---- */}
        <section className="flex flex-col items-center gap-5 py-16 text-center">
          <h2
            className="text-3xl uppercase tracking-[0.04em] md:text-4xl"
            style={{ fontFamily: 'var(--font-display)' }}
          >
            See your runs as art
          </h2>
          <p className="max-w-sm text-sm text-white/50">
            Connect Strava and your first poster is ready in seconds. No card needed to design.
          </p>
          {connectButton}
          <button
            onClick={onGift}
            className="text-sm text-white/30 transition-colors hover:text-white/60"
          >
            🎁 Or gift a poster to a runner
          </button>
        </section>
      </main>

      {/* ---- Footer ---- */}
      <footer className="border-t border-white/5">
        <div className="mx-auto flex max-w-5xl flex-col items-center gap-4 px-5 py-8">
          <a href="https://www.strava.com" target="_blank" rel="noopener noreferrer">
            <img
              src="/assets/strava/powered-by-strava-white.svg"
              alt="Powered by Strava"
              className="h-5 opacity-30 transition-opacity hover:opacity-50"
            />
          </a>
          <button
            onClick={onPrivacy}
            className="text-xs text-white/20 transition-colors hover:text-white/40"
          >
            Privacy Policy
          </button>
        </div>
      </footer>
    </div>
  );
}

function Section({
  title,
  subtitle,
  children,
}: {
  title: string;
  subtitle?: string;
  children: ReactNode;
}) {
  return (
    <section className="border-t border-white/5 py-12 md:py-16">
      <h2
        className="text-2xl uppercase tracking-[0.06em] md:text-3xl"
        style={{ fontFamily: 'var(--font-display)' }}
      >
        {title}
      </h2>
      {subtitle && <p className="mt-2 max-w-xl text-sm leading-relaxed text-white/40">{subtitle}</p>}
      <div className="mt-6">{children}</div>
    </section>
  );
}

function ExampleCard({
  image,
  imageAlt,
  label,
  description,
}: {
  image: string;
  imageAlt: string;
  label: string;
  description: string;
}) {
  return (
    <div className="overflow-hidden rounded-xl border border-white/10">
      <div className="aspect-[4/5] w-full bg-black">
        <img src={image} alt={imageAlt} loading="lazy" className="h-full w-full object-cover" />
      </div>
      <div className="p-4">
        <div className="text-base font-medium text-white">{label}</div>
        <p className="mt-1 text-xs leading-relaxed text-white/40">{description}</p>
      </div>
    </div>
  );
}

/** Lowest print price, shown in the hero microcopy. Derived from the tiers so it
 *  can never drift from the actual checkout prices. */
function cheapestPriceCents(): number {
  return Math.min(...GIFT_TIERS_CLIENT.map((t) => t.priceCents));
}

function formatPrice(cents: number): string {
  return `$${Math.round(cents / 100)}`;
}
